apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: g-monitoring-prometheus
  namespace: g-monitoring-ns
  labels:
    name: g-monitoring-prometheus
    app: g-monitoring-prometheus-app
    project: g-monitoring-project
spec:
  replicas: 2
  serviceAccountName: g-monitoring-sa
  securityContext: {}
  serviceMonitorSelector: 
    matchLabels:
      name: g-monitoring-service-monitor
    ruleSelector: {}