apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-instance
  namespace: g-monitor-ns
  labels:
    name: prometheus-instance
    app: prometheus-app
    project: g-monitor-project
spec:
  replicas: 2
  serviceAccountName: prometheus-sa
  securityContext: {}
  serviceMonitorSelector: 
    matchLabels:
      name: prometheus-service-monitor
    ruleSelector: {}