apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: g-monitor-service-monitor
  namespace: g-monitor-ns
  labels:
    name: g-monitor-service-monitor
    app: prometheus-app
    project: g-monitor-project
spec:
  namespaceSelector:
    matchNames:
      - g-monitor-app1-ns
      - g-monitor-app2-ns
      - g-monitor-app3-ns
      - g-monitor-app4-ns
      - g-monitor-app5-ns
      - g-monitor-app6-ns
  selector:
    matchLabels:
      project: g-monitor-project
  endpoints:
    - port: main-container
      path: /actuator/prometheus
      interval: 30s
    - port: my-http-service
      path: /metrics
      interval: 30s